databases:
  - name: pg_database
    databaseName: budget_app
    user: admin_tom

services:
  - type: web
    name: pg_database
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pg_database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false